export const OTHER_LANGUAGE_VALUE = "OTHER";

export type LocalizedOptionLabel = {
  ar: string;
  en: string;
  fr: string;
};

export const countries = [
  ["AF", { ar: "أفغانستان", en: "Afghanistan", fr: "Afghanistan" }],
  ["AL", { ar: "ألبانيا", en: "Albania", fr: "Albanie" }],
  ["DZ", { ar: "الجزائر", en: "Algeria", fr: "Algérie" }],
  ["AD", { ar: "أندورا", en: "Andorra", fr: "Andorre" }],
  ["AO", { ar: "أنغولا", en: "Angola", fr: "Angola" }],
  ["AG", { ar: "أنتيغوا وباربودا", en: "Antigua and Barbuda", fr: "Antigua-et-Barbuda" }],
  ["AR", { ar: "الأرجنتين", en: "Argentina", fr: "Argentine" }],
  ["AM", { ar: "أرمينيا", en: "Armenia", fr: "Arménie" }],
  ["AU", { ar: "أستراليا", en: "Australia", fr: "Australie" }],
  ["AT", { ar: "النمسا", en: "Austria", fr: "Autriche" }],
  ["AZ", { ar: "أذربيجان", en: "Azerbaijan", fr: "Azerbaïdjan" }],
  ["BS", { ar: "جزر البهاما", en: "Bahamas", fr: "Bahamas" }],
  ["BH", { ar: "البحرين", en: "Bahrain", fr: "Bahreïn" }],
  ["BD", { ar: "بنغلاديش", en: "Bangladesh", fr: "Bangladesh" }],
  ["BB", { ar: "باربادوس", en: "Barbados", fr: "Barbade" }],
  ["BY", { ar: "بيلاروسيا", en: "Belarus", fr: "Biélorussie" }],
  ["BE", { ar: "بلجيكا", en: "Belgium", fr: "Belgique" }],
  ["BZ", { ar: "بليز", en: "Belize", fr: "Belize" }],
  ["BJ", { ar: "بنين", en: "Benin", fr: "Bénin" }],
  ["BT", { ar: "بوتان", en: "Bhutan", fr: "Bhoutan" }],
  ["BO", { ar: "بوليفيا", en: "Bolivia", fr: "Bolivie" }],
  ["BA", { ar: "البوسنة والهرسك", en: "Bosnia and Herzegovina", fr: "Bosnie-Herzégovine" }],
  ["BW", { ar: "بوتسوانا", en: "Botswana", fr: "Botswana" }],
  ["BR", { ar: "البرازيل", en: "Brazil", fr: "Brésil" }],
  ["BN", { ar: "بروناي", en: "Brunei", fr: "Brunéi" }],
  ["BG", { ar: "بلغاريا", en: "Bulgaria", fr: "Bulgarie" }],
  ["BF", { ar: "بوركينا فاسو", en: "Burkina Faso", fr: "Burkina Faso" }],
  ["BI", { ar: "بوروندي", en: "Burundi", fr: "Burundi" }],
  ["CV", { ar: "الرأس الأخضر", en: "Cabo Verde", fr: "Cap-Vert" }],
  ["KH", { ar: "كمبوديا", en: "Cambodia", fr: "Cambodge" }],
  ["CM", { ar: "الكاميرون", en: "Cameroon", fr: "Cameroun" }],
  ["CA", { ar: "كندا", en: "Canada", fr: "Canada" }],
  ["CF", { ar: "جمهورية أفريقيا الوسطى", en: "Central African Republic", fr: "République centrafricaine" }],
  ["TD", { ar: "تشاد", en: "Chad", fr: "Tchad" }],
  ["CL", { ar: "تشيلي", en: "Chile", fr: "Chili" }],
  ["CN", { ar: "الصين", en: "China", fr: "Chine" }],
  ["CO", { ar: "كولومبيا", en: "Colombia", fr: "Colombie" }],
  ["KM", { ar: "جزر القمر", en: "Comoros", fr: "Comores" }],
  ["CG", { ar: "جمهورية الكونغو", en: "Congo", fr: "République du Congo" }],
  ["CD", { ar: "جمهورية الكونغو الديمقراطية", en: "Congo (Democratic Republic)", fr: "République démocratique du Congo" }],
  ["CK", { ar: "جزر كوك", en: "Cook Islands", fr: "Îles Cook" }],
  ["CR", { ar: "كوستاريكا", en: "Costa Rica", fr: "Costa Rica" }],
  ["HR", { ar: "كرواتيا", en: "Croatia", fr: "Croatie" }],
  ["CU", { ar: "كوبا", en: "Cuba", fr: "Cuba" }],
  ["CY", { ar: "قبرص", en: "Cyprus", fr: "Chypre" }],
  ["CZ", { ar: "جمهورية التشيك", en: "Czech Republic", fr: "République tchèque" }],
  ["CI", { ar: "ساحل العاج", en: "Côte d'Ivoire", fr: "Côte d'Ivoire" }],
  ["DK", { ar: "الدنمارك", en: "Denmark", fr: "Danemark" }],
  ["DJ", { ar: "جيبوتي", en: "Djibouti", fr: "Djibouti" }],
  ["DM", { ar: "دومينيكا", en: "Dominica", fr: "Dominique" }],
  ["DO", { ar: "جمهورية الدومينيكان", en: "Dominican Republic", fr: "République dominicaine" }],
  ["EC", { ar: "الإكوادور", en: "Ecuador", fr: "Équateur" }],
  ["EG", { ar: "مصر", en: "Egypt", fr: "Égypte" }],
  ["SV", { ar: "السلفادور", en: "El Salvador", fr: "Salvador" }],
  ["GQ", { ar: "غينيا الاستوائية", en: "Equatorial Guinea", fr: "Guinée équatoriale" }],
  ["ER", { ar: "إريتريا", en: "Eritrea", fr: "Érythrée" }],
  ["EE", { ar: "إستونيا", en: "Estonia", fr: "Estonie" }],
  ["SZ", { ar: "إسواتيني", en: "Eswatini", fr: "Eswatini" }],
  ["ET", { ar: "إثيوبيا", en: "Ethiopia", fr: "Éthiopie" }],
  ["FJ", { ar: "فيجي", en: "Fiji", fr: "Fidji" }],
  ["FI", { ar: "فنلندا", en: "Finland", fr: "Finlande" }],
  ["FR", { ar: "فرنسا", en: "France", fr: "France" }],
  ["GA", { ar: "الغابون", en: "Gabon", fr: "Gabon" }],
  ["GM", { ar: "غامبيا", en: "Gambia", fr: "Gambie" }],
  ["GE", { ar: "جورجيا", en: "Georgia", fr: "Géorgie" }],
  ["DE", { ar: "ألمانيا", en: "Germany", fr: "Allemagne" }],
  ["GH", { ar: "غانا", en: "Ghana", fr: "Ghana" }],
  ["GR", { ar: "اليونان", en: "Greece", fr: "Grèce" }],
  ["GD", { ar: "غرينادا", en: "Grenada", fr: "Grenade" }],
  ["GT", { ar: "غواتيمالا", en: "Guatemala", fr: "Guatemala" }],
  ["GN", { ar: "غينيا", en: "Guinea", fr: "Guinée" }],
  ["GW", { ar: "غينيا بيساو", en: "Guinea-Bissau", fr: "Guinée-Bissau" }],
  ["GY", { ar: "غيانا", en: "Guyana", fr: "Guyana" }],
  ["HT", { ar: "هايتي", en: "Haiti", fr: "Haïti" }],
  ["HN", { ar: "هندوراس", en: "Honduras", fr: "Honduras" }],
  ["HU", { ar: "المجر", en: "Hungary", fr: "Hongrie" }],
  ["IS", { ar: "آيسلندا", en: "Iceland", fr: "Islande" }],
  ["IN", { ar: "الهند", en: "India", fr: "Inde" }],
  ["ID", { ar: "إندونيسيا", en: "Indonesia", fr: "Indonésie" }],
  ["IR", { ar: "إيران", en: "Iran", fr: "Iran" }],
  ["IQ", { ar: "العراق", en: "Iraq", fr: "Irak" }],
  ["IE", { ar: "أيرلندا", en: "Ireland", fr: "Irlande" }],
  ["IT", { ar: "إيطاليا", en: "Italy", fr: "Italie" }],
  ["JM", { ar: "جامايكا", en: "Jamaica", fr: "Jamaïque" }],
  ["JP", { ar: "اليابان", en: "Japan", fr: "Japon" }],
  ["JO", { ar: "الأردن", en: "Jordan", fr: "Jordanie" }],
  ["KZ", { ar: "كازاخستان", en: "Kazakhstan", fr: "Kazakhstan" }],
  ["KE", { ar: "كينيا", en: "Kenya", fr: "Kenya" }],
  ["KI", { ar: "كيريباتي", en: "Kiribati", fr: "Kiribati" }],
  ["XK", { ar: "كوسوفو", en: "Kosovo", fr: "Kosovo" }],
  ["KW", { ar: "الكويت", en: "Kuwait", fr: "Koweït" }],
  ["KG", { ar: "قيرغيزستان", en: "Kyrgyzstan", fr: "Kirghizistan" }],
  ["LA", { ar: "لاوس", en: "Laos", fr: "Laos" }],
  ["LV", { ar: "لاتفيا", en: "Latvia", fr: "Lettonie" }],
  ["LB", { ar: "لبنان", en: "Lebanon", fr: "Liban" }],
  ["LS", { ar: "ليسوتو", en: "Lesotho", fr: "Lesotho" }],
  ["LR", { ar: "ليبيريا", en: "Liberia", fr: "Libéria" }],
  ["LY", { ar: "ليبيا", en: "Libya", fr: "Libye" }],
  ["LI", { ar: "ليختنشتاين", en: "Liechtenstein", fr: "Liechtenstein" }],
  ["LT", { ar: "ليتوانيا", en: "Lithuania", fr: "Lituanie" }],
  ["LU", { ar: "لوكسمبورغ", en: "Luxembourg", fr: "Luxembourg" }],
  ["MG", { ar: "مدغشقر", en: "Madagascar", fr: "Madagascar" }],
  ["MW", { ar: "مالاوي", en: "Malawi", fr: "Malawi" }],
  ["MY", { ar: "ماليزيا", en: "Malaysia", fr: "Malaisie" }],
  ["MV", { ar: "المالديف", en: "Maldives", fr: "Maldives" }],
  ["ML", { ar: "مالي", en: "Mali", fr: "Mali" }],
  ["MT", { ar: "مالطا", en: "Malta", fr: "Malte" }],
  ["MH", { ar: "جزر مارشال", en: "Marshall Islands", fr: "Îles Marshall" }],
  ["MR", { ar: "موريتانيا", en: "Mauritania", fr: "Mauritanie" }],
  ["MU", { ar: "موريشيوس", en: "Mauritius", fr: "Maurice" }],
  ["MX", { ar: "المكسيك", en: "Mexico", fr: "Mexique" }],
  ["FM", { ar: "ميكرونيزيا", en: "Micronesia", fr: "Micronésie" }],
  ["MD", { ar: "مولدوفا", en: "Moldova", fr: "Moldavie" }],
  ["MC", { ar: "موناكو", en: "Monaco", fr: "Monaco" }],
  ["MN", { ar: "منغوليا", en: "Mongolia", fr: "Mongolie" }],
  ["ME", { ar: "الجبل الأسود", en: "Montenegro", fr: "Monténégro" }],
  ["MA", { ar: "المغرب", en: "Morocco", fr: "Maroc" }],
  ["MZ", { ar: "موزمبيق", en: "Mozambique", fr: "Mozambique" }],
  ["MM", { ar: "ميانمار", en: "Myanmar", fr: "Myanmar" }],
  ["NA", { ar: "ناميبيا", en: "Namibia", fr: "Namibie" }],
  ["NR", { ar: "ناورو", en: "Nauru", fr: "Nauru" }],
  ["NP", { ar: "نيبال", en: "Nepal", fr: "Népal" }],
  ["NL", { ar: "هولندا", en: "Netherlands", fr: "Pays-Bas" }],
  ["NZ", { ar: "نيوزيلندا", en: "New Zealand", fr: "Nouvelle-Zélande" }],
  ["NI", { ar: "نيكاراغوا", en: "Nicaragua", fr: "Nicaragua" }],
  ["NE", { ar: "النيجر", en: "Niger", fr: "Niger" }],
  ["NG", { ar: "نيجيريا", en: "Nigeria", fr: "Nigeria" }],
  ["KP", { ar: "كوريا الشمالية", en: "North Korea", fr: "Corée du Nord" }],
  ["MK", { ar: "مقدونيا الشمالية", en: "North Macedonia", fr: "Macédoine du Nord" }],
  ["NO", { ar: "النرويج", en: "Norway", fr: "Norvège" }],
  ["OM", { ar: "عُمان", en: "Oman", fr: "Oman" }],
  ["PK", { ar: "باكستان", en: "Pakistan", fr: "Pakistan" }],
  ["PW", { ar: "بالاو", en: "Palau", fr: "Palaos" }],
  ["PS", { ar: "فلسطين", en: "Palestine", fr: "Palestine" }],
  ["PA", { ar: "بنما", en: "Panama", fr: "Panama" }],
  ["PG", { ar: "بابوا غينيا الجديدة", en: "Papua New Guinea", fr: "Papouasie-Nouvelle-Guinée" }],
  ["PY", { ar: "باراغواي", en: "Paraguay", fr: "Paraguay" }],
  ["PE", { ar: "بيرو", en: "Peru", fr: "Pérou" }],
  ["PH", { ar: "الفلبين", en: "Philippines", fr: "Philippines" }],
  ["PL", { ar: "بولندا", en: "Poland", fr: "Pologne" }],
  ["PT", { ar: "البرتغال", en: "Portugal", fr: "Portugal" }],
  ["QA", { ar: "قطر", en: "Qatar", fr: "Qatar" }],
  ["RO", { ar: "رومانيا", en: "Romania", fr: "Roumanie" }],
  ["RU", { ar: "روسيا", en: "Russia", fr: "Russie" }],
  ["RW", { ar: "رواندا", en: "Rwanda", fr: "Rwanda" }],
  ["KN", { ar: "سانت كيتس ونيفيس", en: "Saint Kitts and Nevis", fr: "Saint-Christophe-et-Niévès" }],
  ["LC", { ar: "سانت لوسيا", en: "Saint Lucia", fr: "Sainte-Lucie" }],
  ["VC", { ar: "سانت فنسنت وجزر غرينادين", en: "Saint Vincent and the Grenadines", fr: "Saint-Vincent-et-les-Grenadines" }],
  ["WS", { ar: "ساموا", en: "Samoa", fr: "Samoa" }],
  ["SM", { ar: "سان مارينو", en: "San Marino", fr: "Saint-Marin" }],
  ["SA", { ar: "المملكة العربية السعودية", en: "Saudi Arabia", fr: "Arabie saoudite" }],
  ["SN", { ar: "السنغال", en: "Senegal", fr: "Sénégal" }],
  ["RS", { ar: "صربيا", en: "Serbia", fr: "Serbie" }],
  ["SC", { ar: "سيشيل", en: "Seychelles", fr: "Seychelles" }],
  ["SL", { ar: "سيراليون", en: "Sierra Leone", fr: "Sierra Leone" }],
  ["SG", { ar: "سنغافورة", en: "Singapore", fr: "Singapour" }],
  ["SK", { ar: "سلوفاكيا", en: "Slovakia", fr: "Slovaquie" }],
  ["SI", { ar: "سلوفينيا", en: "Slovenia", fr: "Slovénie" }],
  ["SB", { ar: "جزر سليمان", en: "Solomon Islands", fr: "Îles Salomon" }],
  ["SO", { ar: "الصومال", en: "Somalia", fr: "Somalie" }],
  ["ZA", { ar: "جنوب أفريقيا", en: "South Africa", fr: "Afrique du Sud" }],
  ["SS", { ar: "جنوب السودان", en: "South Sudan", fr: "Soudan du Sud" }],
  ["ES", { ar: "إسبانيا", en: "Spain", fr: "Espagne" }],
  ["LK", { ar: "سريلانكا", en: "Sri Lanka", fr: "Sri Lanka" }],
  ["SD", { ar: "السودان", en: "Sudan", fr: "Soudan" }],
  ["SR", { ar: "سورينام", en: "Suriname", fr: "Suriname" }],
  ["SE", { ar: "السويد", en: "Sweden", fr: "Suède" }],
  ["CH", { ar: "سويسرا", en: "Switzerland", fr: "Suisse" }],
  ["SY", { ar: "سوريا", en: "Syria", fr: "Syrie" }],
  ["ST", { ar: "سان تومي وبرينسيبي", en: "São Tomé and Príncipe", fr: "Sao Tomé-et-Principe" }],
  ["TW", { ar: "تايوان", en: "Taiwan", fr: "Taïwan" }],
  ["TJ", { ar: "طاجيكستان", en: "Tajikistan", fr: "Tadjikistan" }],
  ["TZ", { ar: "تنزانيا", en: "Tanzania", fr: "Tanzanie" }],
  ["TH", { ar: "تايلاند", en: "Thailand", fr: "Thaïlande" }],
  ["TL", { ar: "تيمور الشرقية", en: "Timor-Leste", fr: "Timor oriental" }],
  ["TG", { ar: "توغو", en: "Togo", fr: "Togo" }],
  ["TO", { ar: "تونغا", en: "Tonga", fr: "Tonga" }],
  ["TT", { ar: "ترينيداد وتوباغو", en: "Trinidad and Tobago", fr: "Trinité-et-Tobago" }],
  ["TN", { ar: "تونس", en: "Tunisia", fr: "Tunisie" }],
  ["TR", { ar: "تركيا", en: "Turkey", fr: "Turquie" }],
  ["TM", { ar: "تركمانستان", en: "Turkmenistan", fr: "Turkménistan" }],
  ["TV", { ar: "توفالو", en: "Tuvalu", fr: "Tuvalu" }],
  ["UG", { ar: "أوغندا", en: "Uganda", fr: "Ouganda" }],
  ["UA", { ar: "أوكرانيا", en: "Ukraine", fr: "Ukraine" }],
  ["AE", { ar: "الإمارات العربية المتحدة", en: "United Arab Emirates", fr: "Émirats arabes unis" }],
  ["GB", { ar: "المملكة المتحدة", en: "United Kingdom", fr: "Royaume-Uni" }],
  ["US", { ar: "الولايات المتحدة الأمريكية", en: "United States", fr: "États-Unis" }],
  ["UY", { ar: "أوروغواي", en: "Uruguay", fr: "Uruguay" }],
  ["UZ", { ar: "أوزبكستان", en: "Uzbekistan", fr: "Ouzbékistan" }],
  ["VU", { ar: "فانواتو", en: "Vanuatu", fr: "Vanuatu" }],
  ["VA", { ar: "الفاتيكان", en: "Vatican City", fr: "Vatican" }],
  ["VE", { ar: "فنزويلا", en: "Venezuela", fr: "Venezuela" }],
  ["VN", { ar: "فيتنام", en: "Vietnam", fr: "Viêt Nam" }],
  ["YE", { ar: "اليمن", en: "Yemen", fr: "Yémen" }],
  ["ZM", { ar: "زامبيا", en: "Zambia", fr: "Zambie" }],
  ["ZW", { ar: "زيمبابوي", en: "Zimbabwe", fr: "Zimbabwe" }],
] as const satisfies readonly (readonly [string, LocalizedOptionLabel])[];

export const languages = [
  ["af", { ar: "الأفريكانية", en: "Afrikaans", fr: "Afrikaans" }],
  ["sq", { ar: "الألبانية", en: "Albanian", fr: "Albanais" }],
  ["am", { ar: "الأمهرية", en: "Amharic", fr: "Amharique" }],
  ["ar", { ar: "العربية", en: "Arabic", fr: "Arabe" }],
  ["hy", { ar: "الأرمينية", en: "Armenian", fr: "Arménien" }],
  ["az", { ar: "الأذربيجانية", en: "Azerbaijani", fr: "Azerbaïdjanais" }],
  ["bn", { ar: "البنغالية", en: "Bengali", fr: "Bengali" }],
  ["bs", { ar: "البوسنية", en: "Bosnian", fr: "Bosnien" }],
  ["bg", { ar: "البلغارية", en: "Bulgarian", fr: "Bulgare" }],
  ["my", { ar: "البورمية", en: "Burmese", fr: "Birman" }],
  ["ca", { ar: "الكاتالانية", en: "Catalan", fr: "Catalan" }],
  ["zh", { ar: "الصينية (الماندرين)", en: "Chinese (Mandarin)", fr: "Chinois (mandarin)" }],
  ["hr", { ar: "الكرواتية", en: "Croatian", fr: "Croate" }],
  ["cs", { ar: "التشيكية", en: "Czech", fr: "Tchèque" }],
  ["da", { ar: "الدنماركية", en: "Danish", fr: "Danois" }],
  ["prs", { ar: "الدارية", en: "Dari", fr: "Dari" }],
  ["nl", { ar: "الهولندية", en: "Dutch", fr: "Néerlandais" }],
  ["en", { ar: "الإنجليزية", en: "English", fr: "Anglais" }],
  ["et", { ar: "الإستونية", en: "Estonian", fr: "Estonien" }],
  ["fi", { ar: "الفنلندية", en: "Finnish", fr: "Finnois" }],
  ["fr", { ar: "الفرنسية", en: "French", fr: "Français" }],
  ["ka", { ar: "الجورجية", en: "Georgian", fr: "Géorgien" }],
  ["de", { ar: "الألمانية", en: "German", fr: "Allemand" }],
  ["el", { ar: "اليونانية", en: "Greek", fr: "Grec" }],
  ["ha", { ar: "الهوسا", en: "Hausa", fr: "Haoussa" }],
  ["hi", { ar: "الهندية", en: "Hindi", fr: "Hindi" }],
  ["hu", { ar: "المجرية", en: "Hungarian", fr: "Hongrois" }],
  ["ig", { ar: "الإيغبو", en: "Igbo", fr: "Igbo" }],
  ["id", { ar: "الإندونيسية", en: "Indonesian", fr: "Indonésien" }],
  ["it", { ar: "الإيطالية", en: "Italian", fr: "Italien" }],
  ["ja", { ar: "اليابانية", en: "Japanese", fr: "Japonais" }],
  ["jv", { ar: "الجاوية", en: "Javanese", fr: "Javanais" }],
  ["kn", { ar: "الكانادا", en: "Kannada", fr: "Kannada" }],
  ["kk", { ar: "الكازاخية", en: "Kazakh", fr: "Kazakh" }],
  ["km", { ar: "الخميرية", en: "Khmer", fr: "Khmer" }],
  ["ko", { ar: "الكورية", en: "Korean", fr: "Coréen" }],
  ["lo", { ar: "اللاوية", en: "Lao", fr: "Laotien" }],
  ["lv", { ar: "اللاتفية", en: "Latvian", fr: "Letton" }],
  ["lt", { ar: "الليتوانية", en: "Lithuanian", fr: "Lituanien" }],
  ["mk", { ar: "المقدونية", en: "Macedonian", fr: "Macédonien" }],
  ["ms", { ar: "الملايوية", en: "Malay", fr: "Malais" }],
  ["ml", { ar: "المالايالامية", en: "Malayalam", fr: "Malayalam" }],
  ["mr", { ar: "الماراثية", en: "Marathi", fr: "Marathi" }],
  ["mn", { ar: "المنغولية", en: "Mongolian", fr: "Mongol" }],
  ["ne", { ar: "النيبالية", en: "Nepali", fr: "Népalais" }],
  ["no", { ar: "النرويجية", en: "Norwegian", fr: "Norvégien" }],
  ["ps", { ar: "البشتوية", en: "Pashto", fr: "Pachto" }],
  ["fa", { ar: "الفارسية", en: "Persian (Farsi)", fr: "Persan (Farsi)" }],
  ["pl", { ar: "البولندية", en: "Polish", fr: "Polonais" }],
  ["pt", { ar: "البرتغالية", en: "Portuguese", fr: "Portugais" }],
  ["pa", { ar: "البنجابية", en: "Punjabi", fr: "Pendjabi" }],
  ["ro", { ar: "الرومانية", en: "Romanian", fr: "Roumain" }],
  ["ru", { ar: "الروسية", en: "Russian", fr: "Russe" }],
  ["sr", { ar: "الصربية", en: "Serbian", fr: "Serbe" }],
  ["si", { ar: "السنهالية", en: "Sinhala", fr: "Cingalais" }],
  ["sk", { ar: "السلوفاكية", en: "Slovak", fr: "Slovaque" }],
  ["sl", { ar: "السلوفينية", en: "Slovenian", fr: "Slovène" }],
  ["so", { ar: "الصومالية", en: "Somali", fr: "Somali" }],
  ["es", { ar: "الإسبانية", en: "Spanish", fr: "Espagnol" }],
  ["sw", { ar: "السواحيلية", en: "Swahili", fr: "Swahili" }],
  ["sv", { ar: "السويدية", en: "Swedish", fr: "Suédois" }],
  ["tl", { ar: "التاغالوغية", en: "Tagalog", fr: "Tagalog" }],
  ["tg", { ar: "الطاجيكية", en: "Tajik", fr: "Tadjik" }],
  ["ta", { ar: "التاميلية", en: "Tamil", fr: "Tamoul" }],
  ["te", { ar: "التيلوغو", en: "Telugu", fr: "Télougou" }],
  ["th", { ar: "التايلاندية", en: "Thai", fr: "Thaï" }],
  ["bo", { ar: "التبتية", en: "Tibetan", fr: "Tibétain" }],
  ["ti", { ar: "التيغرينية", en: "Tigrinya", fr: "Tigrigna" }],
  ["tr", { ar: "التركية", en: "Turkish", fr: "Turc" }],
  ["uk", { ar: "الأوكرانية", en: "Ukrainian", fr: "Ukrainien" }],
  ["ur", { ar: "الأردية", en: "Urdu", fr: "Ourdou" }],
  ["uz", { ar: "الأوزبكية", en: "Uzbek", fr: "Ouzbek" }],
  ["vi", { ar: "الفيتنامية", en: "Vietnamese", fr: "Vietnamien" }],
  ["wo", { ar: "الولوف", en: "Wolof", fr: "Wolof" }],
  ["yo", { ar: "اليوروبا", en: "Yoruba", fr: "Yoruba" }],
  ["zu", { ar: "الزولو", en: "Zulu", fr: "Zoulou" }],
  ["OTHER", { ar: "أخرى", en: "Other", fr: "Autre" }],
] as const satisfies readonly (readonly [string, LocalizedOptionLabel])[];
